import type { Book } from "./types"

export const mockBooks: Book[] = [
  {
    id: "1",
    title: "The Midnight Library",
    author: "Matt Haig",
    description:
      "Between life and death there is a library, and within that library, the shelves go on forever. Every book provides a chance to try another life you could have lived.",
    coverImage: "/placeholder.svg?height=450&width=300",
    rating: 4.2,
    categories: ["Fiction", "Fantasy", "Contemporary"],
    publishedDate: "2020-08-13",
    publisher: "Canongate Books",
    language: "English",
    source: "Google Books",
  },
  {
    id: "2",
    title: "Project Hail Mary",
    author: "Andy Weir",
    description:
      "Ryland Grace is the sole survivor on a desperate, last-chance mission—and if he fails, humanity and the Earth itself will perish.",
    coverImage: "/placeholder.svg?height=450&width=300",
    rating: 4.5,
    categories: ["Science Fiction", "Space", "Adventure"],
    publishedDate: "2021-05-04",
    publisher: "Ballantine Books",
    language: "English",
    source: "Open Library",
  },
  {
    id: "3",
    title: "Klara and the Sun",
    author: "Kazuo Ishiguro",
    description:
      "From the bestselling author of Never Let Me Go and The Remains of the Day, a stunning new novel that asks, what does it mean to love?",
    coverImage: "/placeholder.svg?height=450&width=300",
    rating: 3.9,
    categories: ["Fiction", "Science Fiction", "Literary Fiction"],
    publishedDate: "2021-03-02",
    publisher: "Faber & Faber",
    language: "English",
    source: "Goodreads",
  },
  {
    id: "4",
    title: "The Four Winds",
    author: "Kristin Hannah",
    description:
      "From the number-one bestselling author of The Nightingale and The Great Alone comes a powerful American epic about love and heroism and hope.",
    coverImage: "/placeholder.svg?height=450&width=300",
    rating: 4.3,
    categories: ["Historical Fiction", "Fiction", "Historical"],
    publishedDate: "2021-02-02",
    publisher: "St. Martin's Press",
    language: "English",
    source: "Google Books",
  },
  {
    id: "5",
    title: "The Invisible Life of Addie LaRue",
    author: "V.E. Schwab",
    description: "A Life No One Will Remember. A Story You Will Never Forget.",
    coverImage: "/placeholder.svg?height=450&width=300",
    rating: 4.2,
    categories: ["Fantasy", "Fiction", "Historical Fiction"],
    publishedDate: "2020-10-06",
    publisher: "Tor Books",
    language: "English",
    source: "Open Library",
  },
  {
    id: "6",
    title: "The Vanishing Half",
    author: "Brit Bennett",
    description:
      "The Vignes twin sisters will always be identical. But after growing up together in a small, southern black community and running away at age sixteen, it's not just the shape of their daily lives that is different as adults, it's everything.",
    coverImage: "/placeholder.svg?height=450&width=300",
    rating: 4.1,
    categories: ["Fiction", "Historical Fiction", "Contemporary"],
    publishedDate: "2020-06-02",
    publisher: "Riverhead Books",
    language: "English",
    source: "Goodreads",
  },
  {
    id: "7",
    title: "Educated",
    author: "Tara Westover",
    description:
      "An unforgettable memoir about a young girl who, kept out of school, leaves her survivalist family and goes on to earn a PhD from Cambridge University.",
    coverImage: "/placeholder.svg?height=450&width=300",
    rating: 4.7,
    categories: ["Memoir", "Nonfiction", "Biography"],
    publishedDate: "2018-02-20",
    publisher: "Random House",
    language: "English",
    source: "Google Books",
  },
  {
    id: "8",
    title: "Where the Crawdads Sing",
    author: "Delia Owens",
    description:
      "For years, rumors of the 'Marsh Girl' have haunted Barkley Cove, a quiet town on the North Carolina coast. So in late 1969, when handsome Chase Andrews is found dead, the locals immediately suspect Kya Clark, the so-called Marsh Girl.",
    coverImage: "/placeholder.svg?height=450&width=300",
    rating: 4.6,
    categories: ["Fiction", "Mystery", "Historical Fiction"],
    publishedDate: "2018-08-14",
    publisher: "G.P. Putnam's Sons",
    language: "English",
    source: "Open Library",
  },
  {
    id: "9",
    title: "The Silent Patient",
    author: "Alex Michaelides",
    description:
      "Alicia Berenson's life is seemingly perfect. A famous painter married to an in-demand fashion photographer, she lives in a grand house with big windows overlooking a park in one of London's most desirable areas.",
    coverImage: "/placeholder.svg?height=450&width=300",
    rating: 4.0,
    categories: ["Thriller", "Mystery", "Fiction"],
    publishedDate: "2019-02-05",
    publisher: "Celadon Books",
    language: "English",
    source: "Goodreads",
  },
  {
    id: "10",
    title: "Atomic Habits",
    author: "James Clear",
    description:
      "No matter your goals, Atomic Habits offers a proven framework for improving--every day. James Clear, one of the world's leading experts on habit formation, reveals practical strategies that will teach you exactly how to form good habits, break bad ones, and master the tiny behaviors that lead to remarkable results.",
    coverImage: "/placeholder.svg?height=450&width=300",
    rating: 4.8,
    categories: ["Self Help", "Nonfiction", "Psychology"],
    publishedDate: "2018-10-16",
    publisher: "Avery",
    language: "English",
    source: "Google Books",
  },
]

